using UnityEngine;

public class DetectorImpactoMelee : MonoBehaviour
{
    [SerializeField] private string tagEnemigo = "enemy";
    private HealthComp enemigo;
    private ControladorCombate player;

    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag(tagEnemigo))
        {
            player = GameObject.FindGameObjectWithTag("Player").GetComponent<ControladorCombate>();

            enemigo = other.GetComponent<HealthComp>();
            enemigo.recibeDano(player.EntregarDañoArmaMelee(enemigo.getBloqueando()));
            enemigo.setRecibiendoDano(true);

            if (enemigo.EstaEsquivando) return;

            if (enemigo.getBloqueando())
            {
                player.ReproducirSonidoAleatorio(2, 1);
                player.ReproducirVFX(2, 1);
            }

            else
            {
                player.ReproducirSonidoAleatorio(1, 1);
                player.ReproducirVFX(2, 1);
            }

        }
    }
}

